### PR TITLE
fix unhandled edge cases for keyboard shortcuts (fixes #927, fixes #932, fixes #1063)

### LINKED ISSUE #927: WASD controls should stop on document blur
I noticed this a while back but kept forgetting to file.

STR:

1. Load https://aframe.io/aframe/examples/showcase-spheres-and-fog/ and stay in mono view
2. Hold down the `A` key
3. Whilst holding the `A` key, move your cursor outside of your browser window
4. Notice you are still moving left

### LINKED ISSUE #932: WASD controls should not be engaged w/ shift/control/alt/meta keys
(Similar but different from #927.)

STR:

1. Load https://aframe.io/aframe/examples/showcase-spheres-and-fog/
2. Hold down the `Command` + `A` keys
3. Release the keys
4. Notice you keep moving left

For WASD controls, we should abort if `shiftKey`, `ctrlKey`, `altKey`, or `metaKey` are also being held.

### LINKED ISSUE #1063: Keypresses in form fields should not be considered keypresses for keyboard shortcuts + WASD controls
1. Place a form field somewhere on the page (outside of the `<a-scene>` of course): `<input style="position:absolute;z-index:1">`
2. Start typing these keys: `w`, `a`, `s`, `d`, `f`, `z`

### PR DESCRIPTION
**Pull request by cvan**

### CODE REVIEW

File: src/utils/index.js [hunk 1]
```diff
@@ -131,14 +131,25 @@ var isIOS = module.exports.isIOS = function () {
...
  */
 module.exports.isLandscape = function () {
   return window.orientation === 90 || window.orientation === -90;
 };
 
 /**
+ * Returns whether we can safely listen to this keyboard event.
+ * @returns {Boolean} True if we can.
+ */
+module.exports.shouldCaptureKeyEvent = function (event) {
```
Comment (cvan) [inline src/utils/index.js]: renamed per @dmarcos' suggestion in the previous PR: #1064

File: src/components/wasd-controls.js [hunk 2]
```diff
@@ -98,21 +100,29 @@ module.exports.Component = registerComponent('wasd-controls', {
...
 
   removeEventListeners: function () {
     // Keyboard events
+    window.removeEventListener('blur', this.onBlur);
     window.removeEventListener('keydown', this.onKeyDown);
     window.removeEventListener('keyup', this.onKeyUp);
   },
 
+  onBlur: function (event) {
+    this.keys = {};
```
Comment (cvan) [inline src/components/wasd-controls.js]: calling `this.pause()` does not work. must do this.

Comment (cvan) [inline src/components/wasd-controls.js]: I will change the `pause` method to clear `this.keys`.

File: src/components/wasd-controls.js [hunk 3]
```diff
@@ -98,21 +101,29 @@ module.exports.Component = registerComponent('wasd-controls', {
...
   },
 
   removeEventListeners: function () {
     // Keyboard events
+    window.removeEventListener('blur', this.onBlur);
     window.removeEventListener('keydown', this.onKeyDown);
     window.removeEventListener('keyup', this.onKeyUp);
   },
 
+  onBlur: function () {
```
Comment (dmarcos) [inline src/components/wasd-controls.js]: Should we move this to the component module and always call ```pause``` on blur for every component?

Comment (cvan) [inline src/components/wasd-controls.js]: interesting idea; probably actually, yeah. you think that's good?

Comment (dmarcos) [inline src/components/wasd-controls.js]: When is the blur event exactly triggered?

File: src/utils/index.js [hunk 4]
```diff
@@ -131,14 +131,25 @@ var isIOS = module.exports.isIOS = function () {
...
- * @return {Boolean} True if landscape orientation
+ * Checks mobile device orientation.
+ * @return {Boolean} True if landscape orientation.
  */
 module.exports.isLandscape = function () {
   return window.orientation === 90 || window.orientation === -90;
 };
 
 /**
+ * Returns whether we can safely listen to this keyboard event.
```
Comment (ngokevin) [inline src/utils/index.js]: Could expand on what is "safely".

File: src/utils/index.js [hunk 5]
```diff
@@ -131,14 +131,25 @@ var isIOS = module.exports.isIOS = function () {
...
+ * @returns {Boolean} True if we can.
```
Comment (ngokevin) [inline src/utils/index.js]: s/True/true

File: src/components/wasd-controls.js (hunk 3 above)
Comment (cvan) [inline src/components/wasd-controls.js]: when the current tab is no longer the focused tab - or if the window loses focus

File: src/utils/index.js (hunk 5 above)
Comment (cvan) [inline src/utils/index.js]: it's capitalised because a sentence - and we do elsewhere. I would say `true`. will change.

File: src/components/wasd-controls.js (hunk 3 above)
Comment (ngokevin) [inline src/components/wasd-controls.js]: Hard to say whether to want to force pause on blur. Seems too prescriptive at the moment.

File: src/utils/index.js (hunk 5 above)
Comment (ngokevin) [inline src/utils/index.js]: just brought it up because `true` is a value

**Comment by dmarcos** [comment]
@cvan What's the state of this. Is this ready to go? Let's use the ```needs review``` label otherwise it's hard to tell when PRs are ready.

File: src/components/wasd-controls.js [hunk 6]
```diff
@@ -98,21 +101,29 @@ module.exports.Component = registerComponent('wasd-controls', {
 
   attachEventListeners: function () {
     // Keyboard events
-    window.addEventListener('keydown', this.onKeyDown, false);
-    window.addEventListener('keyup', this.onKeyUp, false);
+    window.addEventListener('blur', this.onBlur);
```
Comment (dmarcos) [inline src/components/wasd-controls.js]: Should we also have a listener for the symmetric event.  ```window.addEventListener("focus", this.onFocus);```?

Comment (cvan) [inline src/components/wasd-controls.js]: oh, very good call.

hmm, the more I think about it we probably shouldn't call `pause` on `blur` because that [removes the event listeners](https://github.com/aframevr/aframe/pull/1211/files#diff-6231789e7e7fac0fbea47834d09b3bdcR91). and then we'd have to reattach them. seems like maybe a waste. thoughts?

**Comment by cvan** [comment]
@dmarcos updated to handle blur/focus/visibilitychange pause/play correctly. good catch, thanks
