### PR TITLE
fix case where removing texture (null was not equal to empty string)

### LINKED ISSUE #2388: Removing or setting a null for SRC in a material doesn't works
**Description:** 
If we've an entity with a material set and a `src` loaded, if we try to clear the `src` value by removing the `src`attribute itself or by setting it to null or "", it will clear the value but it will still keep the texture binded to the entity

- A-Frame Version: v0.5.0
- Platform / Device: 
- Reproducible Code Snippet or URL: http://codepen.io/fernandojsg/pen/NdooBz

### PR DESCRIPTION
**Pull request by machenmusik**
Fixes #2388

### CODE REVIEW

**Comment by machenmusik** [comment]
easiest way to test - run local instance with this change via `npm start`, and load @fernandojsg's codepen on same machine, changing aframe script src to `http://localhost:9000/build/aframe.js`

**Comment by ngokevin** [comment]
Can we add unit tests? Both for `setAttribute('material', 'src', '')` and `removeAttribute('material', 'src')`.

**Comment by machenmusik** [comment]
ok, LGTM now...

**Comment by machenmusik** [comment]
@dmarcos take a look at latest? should be much more comprehensible

**Comment by machenmusik** [comment]
specifically, latest added comments try to better explain why having a single remembrance of last texture load attempt is insufficient, per discussion on #2402

File: src/utils/material.js [hunk 1]
```diff
@@ -10,24 +11,42 @@ module.exports.updateMapMaterialFromData = function (materialName, dataName, sha
...
 
-  if (src) {
-    if (src === shader[shadowSrcName]) { return; }
-    // Texture added or changed.
-    shader[shadowSrcName] = src;
-    if (src instanceof THREE.Texture) { setMap(src); return; }
-    el.sceneEl.systems.material.loadTexture(src, {src: src, repeat: data.repeat, offset: data.offset, npot: data.npot}, setMap);
+  if (!src) {
+    // Forget the prior material src.
+    shader[shadowSrcName] = null;
```
Comment (dmarcos) [inline src/utils/material.js]: Would not be better to store all the material src within an object and not hanging directly from the shader with a strange `__texture__` key? Something like `shader.materialsSrc = []`

Comment (machenmusik) [inline src/utils/material.js]: I thought that the developers can arbitrarily define and use anything in the shader property namespace, so was trying to avoid collisions by using unlikely-to-collide naming, though I could be wrong.  Maybe it is better to make a map with name that is unlikely to collide as you suggest, although as it is internal, I thought usual convention was to use underscore prefix.

Comment (dmarcos) [inline src/utils/material.js]: you can then append it to the `shader.material` object. Safer than a strange `key`

Comment (machenmusik) [inline src/utils/material.js]: While I was in there, really we don't care about the data property name, we care about the material property name, which is what we use to actually set the texture.

**Comment by machenmusik** [comment]
LGTM... @dmarcos ?

**Comment by dmarcos** [comment]
Thanks!
