### PR TITLE
Make camera system aware of mixins.

### LINKED ISSUE #3090: The camera component can not be used inside a mixin
The following example fails:
https://codepen.io/lodr/pen/yzbvba

It is caused by:
```html
<a-mixin id="c" camera></a-mixin>
```

And the console says:
```
TypeError: cameraEl.pause is not a function
[Learn More]
```

captura de pantalla 2017-09-28 a las 13 57 36

### PR DESCRIPTION
**Pull request by delapuente**
Fix #3090

Prevents the camera system from taking into account a-mixin elements when
handling the active camera.

### CODE REVIEW

File: src/systems/camera.js [hunk 1]
```diff
@@ -100,11 +100,15 @@ module.exports.System = registerSystem('camera', {
     cameraEls = sceneEl.querySelectorAll('[camera]');
     for (i = 0; i < cameraEls.length; i++) {
       cameraEl = cameraEls[i];
-      if (newCameraEl === cameraEl) { continue; }
+      if (isMixin(cameraEl) || newCameraEl === cameraEl) { continue; }
```
Comment (ngokevin) [inline src/systems/camera.js]: You can do `!cameraEl.isEntity`

Comment (delapuente) [reply src/systems/camera.js]: Will it return `true` for primitives also?

Comment (ngokevin) [reply src/systems/camera.js]: Yeah.
