### PR TITLE
clone default array property type, use default array value if not defined (fixes #3092)

### LINKED ISSUE #3092: Schema `default` property is not working for `array` type
The following schema is not working as expected:
```js
schema: { type: 'array', default: ['a'] }
```

Demo (open the console):
https://codepen.io/lodr/pen/oGWyoM

Expected log:
```
["a"]
```

Actual log:
```
[]
```

### PR DESCRIPTION
**Pull request by ngokevin**
**Description:**

1. Arrays were not getting cloned.
2. Default arrays value were not being used if no data was explicitly defined...since array parser will parse `''` to `[]`. `buildData` would then treat `[]` as a defined value.

**Changes proposed:**
- Apply several checks used by Object type also to the Array type for cloning.
- Add a case in `buildData` to treat `[]` not as a defined component value.

### CODE REVIEW

File: src/core/component.js [hunk 1]
```diff
@@ -547,3 +549,7 @@ function wrapPlay (playMethod) {
     sceneEl.addBehavior(this);
   };
 }
+
+function objectOrArray (value) {
```
Comment (dmarcos) [inline src/core/component.js]: Maybe `isObjectOrArray` is a better name

**Comment by ngokevin** [comment]
r?
