### PR TITLE
re-add controller events after unpausing scene (fixes #2879)

### LINKED ISSUE #2879: controller buttons/events don't work after pausing and unpausing scene
**Description:**

Blocks Inspector + Motion Capture work.

1. Enter VR. See controllers work when pressing buttons.
2. Open Inspector. Exit Inspector.
3. Enter VR again. Controller buttons do not work

- A-Frame Version: master/0.6.0
- Platform / Device: windows/vive
- Reproducible Code Snippet or URL: 
https://aframe.io/examples/showcase/tracked-controllers/

### PR DESCRIPTION
**Pull request by ngokevin**
**Description:**

The controller code is somewhat awkward since each component needs to follow a certain API and implements various methods, but this way works of making sure controller events get re-added on unpause.

**Changes proposed:**
- Set a state variable for checking whether events are on or not. Then the tracked-controls util can determine whether it needs to re-add events on unpause.
- [x] adjust tests

### CODE REVIEW

File: src/components/vive-controls.js [hunk 1]
```diff
@@ -105,6 +106,7 @@ module.exports.Component = registerComponent('vive-controls', {
     el.removeEventListener('touchstart', this.onButtonTouchStart);
     el.removeEventListener('model-loaded', this.onModelLoaded);
     el.removeEventListener('axismove', this.onAxisMoved);
+    this.controlllerEventsActive = false;
```
Comment (dmarcos) [inline src/components/vive-controls.js]: Do we need a new flag? Can we just rely on the `isPaused` flag of the component?

File: src/components/vive-controls.js [hunk 2]
```diff
@@ -94,6 +94,7 @@ module.exports.Component = registerComponent('vive-controls', {
     el.addEventListener('touchstart', this.onButtonTouchStart);
     el.addEventListener('model-loaded', this.onModelLoaded);
     el.addEventListener('axismove', this.onAxisMoved);
+    this.controlllerEventsActive = true;
```
Comment (dmarcos) [inline src/components/vive-controls.js]: I see that `this.removeEventListeners` is called on `pause` but `this.addEventListeners` is not called in play. We should probably call it there.

File: src/components/vive-controls.js (hunk 1 above)
Comment (dmarcos) [inline src/components/vive-controls.js]: I think that removing / adding event listeners in the controller specific controls is not strictly necessary if `tracked-controls` pauses / plays as expected.

Comment (ngokevin) [inline src/components/vive-controls.js]: We need to call `addEventListener` in the `play` handler only when coming out of a pause. We don't want to call it directly because `utils.tracked-controls` will already call it and we don't want to call it on the first initialization.

Comment (ngokevin) [inline src/components/vive-controls.js]: Removing and adding controller specific event listeners is needed because we don't want to be adding Oculus Touch triggerdown when Oculus Touch controllers not connected, which would result in double-emit if we're using a Vive controller.

File: src/components/vive-controls.js (hunk 2 above)
Comment (ngokevin) [inline src/components/vive-controls.js]: It is called in `play` via the tracked-controls util.

**Comment by dmarcos** [comment]
Nice! 🎁
