### PR TITLE
Fixes #2010 wrong positioning on vive

### LINKED ISSUE #2010: Vive Controller incorrect positions in 0.3.2
**Description:**

Simple scene with controllers

    <a-scene id="scene">

      <a-entity vive-controls="hand: right"></a-entity>
      <a-entity vive-controls="hand: left"></a-entity>

      <a-plane position="0 0 -4" rotation="-90 0 0" width="4" height="4" color="#7BC8A4"></a-plane>
      <a-sky color="#ECECEC"></a-sky>
    </a-scene>

Controllers drift uncontrollably, as if positions are accumulating on itself.

This works correctly in 0.3.1, but not 0.3.2

- A-Frame Version: 0.3.2 and Master
- Platform/Device: Windows Chromium WebVR Build
- Reproducible Code Snippet or Demo URL [highly encouraged]:

### PR DESCRIPTION
**Pull request by fernandojsg**
`previousControllerPosition` was being shared by the two controllers, so it was giving an incorrect value.
And I was accumulating .x everywhere

### CODE REVIEW

File: src/components/tracked-controls.js [hunk 1]
```diff
@@ -77,14 +77,14 @@ module.exports.Component = registerComponent('tracked-controls', {
...
+      deltaControllerPosition.copy(controllerPosition).sub(this.previousControllerPosition);
+      this.previousControllerPosition.copy(controllerPosition);
       var currentPosition = el.getAttribute('position');
 
       el.setAttribute('position', {
         x: currentPosition.x + deltaControllerPosition.x,
-        y: currentPosition.x + deltaControllerPosition.y,
-        z: currentPosition.x + deltaControllerPosition.z
+        y: currentPosition.y + deltaControllerPosition.y,
+        z: currentPosition.z + deltaControllerPosition.z
```
Comment (ngokevin) [inline src/components/tracked-controls.js]: https://github.com/aframevr/aframe/pull/2002#discussion_r84802722

**Comment by fernandojsg** [comment]
:+1:
