### PR TITLE
fix component dependencies being initialized with no data (fixes #2033, #1841, #1848)

### LINKED ISSUE #2033: Dependent instantiations do not correctly populate data
Its appear that `init()` is getting called with `this.data` not populated when it is early-instantiated via the dependency logic.

`this.data.foo` will be undefined in `init()` for this entity `<a-entity component-that-is-depended-on="foo: bar" component-with-dependency></a-entity>`

https://github.com/aframevr/aframe/blob/master/src/core/a-entity.js#L358

My guess is that the solution may end up involve retrieving the `attrValue` if `isDependency` is `true` before calling this:
https://github.com/aframevr/aframe/blob/master/src/core/a-entity.js#L331

### PR DESCRIPTION
**Pull request by ngokevin**
**Description:**

With investigation help from @GavanWilhite.

`initComponent` in `initComponentDependencies` was being called with `undefined` rather than reading data from the DOM. The component later initializes with a null data set because components themselves never fetch data from the DOM; they depend on the entity to pass data to them.

**Changes proposed:**
- Call `initComponent` for dependencies using data from the DOM (`HTMLElement.prototype.getAttribute`).
- Increase confidence of dependency system with tests.
- [x] Specific tests for cursor + raycaster combo.

### CODE REVIEW

File: src/core/a-entity.js [hunk 1]
```diff
@@ -594,16 +610,20 @@ var proto = Object.create(ANode.prototype, {
...
+        // Just update one of the component properties.
         if (typeof value === 'string' && componentPropValue !== undefined) {
           this.updateComponentProperty(attr, value, componentPropValue);
         } else {
           this.updateComponent(attr, value);
         }
-        // On debug mode we write the component state to the DOM attributes
+
+        // On debug mode we write the component state to the DOM attributes.
+        isDebugMode = this.sceneEl && this.sceneEl.getAttribute('debug');
```
Comment (dmarcos) [inline src/core/a-entity.js]: I would leave the variables at top. If you want to reuse the same variable somewhere else in the function you have to remember to move it to the top or at least above the other place you want to use it.

File: src/core/a-entity.js [hunk 2]
```diff
@@ -346,16 +346,32 @@ var proto = Object.create(ANode.prototype, {
...
       if (!dependencies) { return; }
-      dependencies.forEach(function (component) {
-        self.initComponent(component, undefined, true);
+
+      // Initialize dependencies.
+      dependencies.forEach(function initializeDependency (componentName) {
+        // Call getAttribute to initialize the data from the DOM.
+        self.initComponent(
+          componentName,
+          HTMLElement.prototype.getAttribute.call(self, componentName),
```
Comment (dmarcos) [inline src/core/a-entity.js]: If the dependency is not defined in the entity this will pass a `null` to the `initComponet` function. What are the consequences?

Comment (ngokevin) [inline src/core/a-entity.js]: I guess I should do `|| undefined` and add a test case.

**Comment by ngokevin** [comment]
updated

File: src/core/a-entity.js (hunk 2 above)
Comment (dmarcos) [inline src/core/a-entity.js]: At some point (I cannot longer tell you if the case) a null value was interpreted as a component being removed. This is why `undefined` value was passed before.
