### PR TITLE
fix screenX screenY

### LINKED ISSUE #3778: Camera spins down on Firefox
Hello all, when I go to the A-Frame site or any glitch project, if I try dragging my mouse on the scene to look around the camera starts spinning and points downwards. If I stop dragging the mouse it stays pointed down. If I try to readjust the camera view it starts spinning again.

I have tried disabling Tracking Protection, Privacy Badger, and HTTPS Everywhere, as those sometimes give me issues on other sites, but it doesn't seem to change anything here. 

It doesn't seem to happen on other WebVR things (such as [React's 360 here](https://github.com/facebook/react-360)). It also seems fine on Edge.

Let me know if there is anything else I can provide to help.

- A-Frame Version: Looking at the source for some of the A-Frame examples: 0.5.0, 0.7.1, and 0.8.2
- Platform / Device: Kubuntu 18.04 and Windows 10 on Firefox 62.0.2

### PR DESCRIPTION
**Pull request by AdaRoseCannon**
Fixes #3778 #4499 

**Changes proposed:**
- Instead of storing reference to previous event stores the values needed from that event
- Unifies mixed use of `evt` and `event` to use `event`

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -90,7 +90,7 @@ require('./core/a-mixin');
 require('./extras/components/');
 require('./extras/primitives/');
 
-console.log('A-Frame Version: 1.0.4 (Date 2020-05-13, Commit #ef405451)');
```
Comment (dmarcos) [inline src/index.js:93]: Can we remove this from PR?

File: src/components/look-controls.js [hunk 2]
```diff
@@ -336,36 +339,36 @@ module.exports.Component = registerComponent('look-controls', {
...
+      x: event.touches[0].pageX,
+      y: event.touches[0].pageY
     };
     this.touchStarted = true;
   },
 
   /**
    * Translate touch move to Y-axis rotation.
    */
-  onTouchMove: function (evt) {
```
Comment (dmarcos) [inline src/components/look-controls.js:353]: Can we keep `evt` instead of `event` for consistency with rest of the code base?

File: src/components/look-controls.js [hunk 3]
```diff
@@ -290,16 +292,17 @@ module.exports.Component = registerComponent('look-controls', {
...
     var sceneEl = this.el.sceneEl;
     if (!this.data.enabled || (sceneEl.is('vr-mode') && sceneEl.checkHeadsetConnected())) { return; }
     // Handle only primary button.
-    if (evt.button !== 0) { return; }
+    if (event.button !== 0) { return; }
 
     var canvasEl = sceneEl && sceneEl.canvas;
 
     this.mouseDown = true;
-    this.previousMouseEvent = evt;
```
Comment (dmarcos) [inline src/components/look-controls.js:302]: This makes some sense. We're holding a reference to the event object that somehow gets deallocated or values get overwritten by the browser. I still don't understand why it does only happen in some Firefox instances / computers. Wondering if there's a deeper issue that could affect other parts of the code base.

**Comment by dmarcos** [comment]
Thanks for doing this. Super appreciated 👍

File: src/components/look-controls.js (hunk 3 above)
Comment (AdaRoseCannon) [reply src/components/look-controls.js:302]: A cursory search for `= evt;` reveals the same thing may occur in *src/components/cursor.js* but it's not an issue I have noticed.

Comment (AdaRoseCannon) [reply src/components/look-controls.js:302]: Correction, in *src/components/cursor.js* the event is not kept beyond the function therefore won't present an issue.

**Comment by dmarcos** [comment]
Thank you. Much appreciated.
