### PR TITLE
Fixes #2470 Added timer

### LINKED ISSUE #2470: Consider using THREE.Clock or performance.now in render(time)
**Description:** 
Currently we use `requestAnimationFrame`'s timestamp as the time to be used on `scene.render`, to update the `TWEEN` and the scene itself.
The following code (https://github.com/aframevr/aframe/blob/master/vendor/VREffect.js#L186-L194) is used to detect which `requestAnimationFrame` we should call, if we've one HMD connected it will call the `vrDisplay`'s one. 

```javascript
this.requestAnimationFrame = function( f ) {
		if ( vrDisplay !== undefined ) {
			return vrDisplay.requestAnimationFrame( f );
		} else {
			return window.requestAnimationFrame( f );
		}
	};
```

The problem is that even if you have a HMD connected, it takes a while to init it so for a few frames it will call `window.requestAnimationFrame` and after that `vrDisplay.requestAnimationFrame`.
`window.requestAnimationFrame` will returns the timestamp since the page was **loaded**, but 
`vrDisplay.requestAnimationFrame` on firefox nightly returns the timestamp relative to the **first load of the browser** not the current page (@kearwood could correct me if I'm wrong here).
So that generates that jump in the timestamp that we see in nightly:
image
We can see that:
- 0 is generated by https://github.com/aframevr/aframe/blob/master/src/core/scene/a-scene.js#L392
- Then we have 3 frames with 3xxx generated by the `windows.RAF`
- Finally `vrDisplay.RAF` jumps in and sends the, much higher, timestamp as I had the browser opened for a while.

So we have two problems:
- The jumps between these values generates incorrect deltas and can generate weird issues (Like the one we've seen in TWEEN: https://github.com/aframevr/aframe/issues/2175)
- The timestamp is typically used to control the timeline of the experience, and we're using an incorrect value for that.

So my proposal is to use `THREE.Clock` or `DATE / performance.now` directly on the render loop to be consistent across browsers and independent from the `RAF` being used.

### PR DESCRIPTION
**Pull request by fernandojsg**
Introducing a timer to fix the problems with the `requestAnimationFrame`

### CODE REVIEW

File: src/utils/index.js [hunk 1]
```diff
@@ -7,6 +7,7 @@ var objectAssign = require('object-assign');
 
 var warn = debug('utils:warn');
 
+module.exports.Timer = require('./timer');
```
Comment (ngokevin) [inline src/utils/index.js]: Could keep this alphabetical

File: src/core/scene/a-scene.js [hunk 2]
```diff
@@ -465,15 +466,15 @@ module.exports = registerElement('a-scene', {
...
-        var timeDelta = time - this.time;
+        this.timer.update();
+        var time = this.timer.elapsedTime;
+        var timeDelta = this.timer.deltaTime;
 
         if (this.isPlaying) { this.tick(time, timeDelta); }
-
         this.animationFrameID = effect.requestAnimationFrame(this.render);
         effect.render(this.object3D, this.camera);
-        this.time = time;
```
Comment (ngokevin) [inline src/core/scene/a-scene.js]: I'd keep the time property on the scene.

File: src/core/scene/a-scene.js [hunk 3]
```diff
@@ -465,15 +466,15 @@ module.exports = registerElement('a-scene', {
      * Renders with request animation frame.
      */
     render: {
-      value: function (time) {
+      value: function () {
         var effect = this.effect;
-        var timeDelta = time - this.time;
+        this.timer.update();
+        var time = this.timer.elapsedTime;
```
Comment (ngokevin) [inline src/core/scene/a-scene.js]: Don't need intermediate vars, only used once.

File: src/utils/timer.js [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+  this.deltaTime = 0;
+}
+
+Object.assign(Timer.prototype, {
+  start: function () {
+    this.startTime = this.previousTime = window.performance.now();
+    this.running = true;
+  },
+
+  update: function () {
```
Comment (ngokevin) [inline src/utils/timer.js]: Unit tests

File: src/utils/index.js (hunk 1 above)
Comment (fernandojsg) [inline src/utils/index.js]: done, I didn't noticed O:)

File: src/core/scene/a-scene.js (hunk 3 above)
Comment (fernandojsg) [inline src/core/scene/a-scene.js]: :+1:

File: src/core/scene/a-scene.js (hunk 2 above)
Comment (fernandojsg) [inline src/core/scene/a-scene.js]: Umm do you want it even if it's accesible with `this.timer.ellapsedTime`?

File: src/utils/index.js (hunk 1 above)
Comment (dmarcos) [inline src/utils/index.js]: Can we use [THREE.Clock](https://threejs.org/docs/#Reference/Core/Clock)?

Comment (fernandojsg) [inline src/utils/index.js]: @dmarcos this was my first try, but the current implementation it's quite ugly (https://github.com/mrdoob/three.js/blob/master/src/core/Clock.js) you need to call `getElapsedTime()` and `getDelta()` but you'll get different values as it will call `performance.now()` again. Or you call `getDelta()` and then access `elapsedTime` that doesn't seems very coherent.
Also it works with seconds instead of ms, so we need to multiply everything by 1000.
I would better stick for now with our implementation and probably open a PR in three.js but I guess it's widely used so it will break many things if we change the implementation a lot.

File: src/core/scene/a-scene.js (hunk 2 above)
Comment (ngokevin) [inline src/core/scene/a-scene.js]: Yeah, it's documented, might be being used. And if browsers ever fix the behavior, it's possible we might revert?

Comment (fernandojsg) [inline src/core/scene/a-scene.js]: Yep, good point

**Comment by ngokevin** [comment]
r+ from me

**Comment by fernandojsg** [comment]
Test added, I'm using right now `assert.isAbove(scene.time, 0);` because of the "bug" we were talking on slack related to https://github.com/mrdoob/three.js/pull/10962.
I'll change that in the future as soon as it will get merged there and we'll upgrade too.

**Comment by dmarcos** [comment]
Thanks!

**Comment by dmarcos** [comment]
waiting for tests
