### PR TITLE
fix scene default component double init (fixes #1059)

### LINKED ISSUE #1059: Scene components listed in `defaultComponents` get initialised twice in Chrome (or with native Custom Elements support?)
When a component is defined as a key in `defaultComponents`, the component's `init` method gets called twice.

Reproduced with `<a-scene>` for `canvas`, `keyboard-shortcuts`, and `vr-mode-ui`.

### PR DESCRIPTION
**Pull request by ngokevin**
Had to move the component-already-initialized check closer to the component initialization. I think because several components are trying to initialize the same component (on top of the scene setAttribute call) at the same time.

### CODE REVIEW

File: src/core/component.js [hunk 1]
```diff
@@ -212,7 +215,7 @@ module.exports.registerComponent = function (name, definition) {
   });
 
   if (components[name]) {
-    throw new Error('The component ' + name + ' has been already registered');
+    warn('The component ' + name + ' has been already registered');
```
Comment (dmarcos) [inline src/core/component.js]: I think this makes more sense to be an error than a warning. If a component is registered twice is a big problem.

Comment (ngokevin) [inline src/core/component.js]: OK. It's usually a benign operation and a warning usually suffice. Halting everything is pretty harsh. But I'll just leave it as an error until it becomes a problem.

Comment (dmarcos) [inline src/core/component.js]: A component registered twice it means that there are two versions of the same components or two different components with the same name colliding. That's a good reason to stop everything loudly and force the user to reevaluate.

File: src/core/a-entity.js [hunk 2]
```diff
@@ -266,12 +264,17 @@ var proto = Object.create(ANode.prototype, {
           // For scene default components, expose them in the DOM.
           HTMLElement.prototype.setAttribute.call(this, name, this.defaultComponents[name]);
         }
+
+        // Check if component already defined.
+        if (name in this.components) { return; }
```
Comment (dmarcos) [inline src/core/a-entity.js]: Why is this necessary? isComponentDefined should catch if the component is already defined.

Comment (ngokevin) [inline src/core/a-entity.js]: I changed some comments.

`isComponentDefined` checks if the component *should be defined* for the entity. What we want to check here if the component *has already been initialized* for the entity.

File: src/core/a-entity.js [hunk 3]
```diff
@@ -551,17 +551,20 @@ var proto = Object.create(ANode.prototype, {
...
 function checkComponentDefined (el, name) {
   // Check if default components contain the component.
-  var inDefaults = el.defaultComponents[name];
+  if (el.defaultComponents[name] !== undefined) { return true; }
+
   // Check if element contains the component.
-  var inAttribute = el.hasAttribute(name);
-  if (inDefaults !== undefined || inAttribute) { return true; }
+  if (el.hasAttribute(name)) { return true; }
+
```
Comment (dmarcos) [inline src/core/a-entity.js]: Why is this if statement gone?
The comment of the function is obsolete.

Comment (ngokevin) [inline src/core/a-entity.js]: Just wanted to reduce one LOC

File: src/core/component.js [hunk 4]
```diff
@@ -212,7 +213,7 @@ module.exports.registerComponent = function (name, definition) {
   });
 
   if (components[name]) {
-    throw new Error('The component ' + name + ' has been already registered');
+    throw new Error('The component `' + name + '` has been already registered');
```
Comment (dmarcos) [inline src/core/component.js]: Can we make this error message a bit better. What about? 
```The component `' + name + '` has been already registered. You might be loading two version of the same component or two different components with the same name are colliding.```

Comment (ngokevin) [inline src/core/component.js]: :+1:

File: src/core/a-entity.js (hunk 3 above)
Comment (dmarcos) [inline src/core/a-entity.js]: nevermind.
