### PR TITLE
simple fix for Gear VR and Oculus Touch controller issues (fixes #3447 and #3483)

### LINKED ISSUE #3447: 0.8.0 laser-controls with Oculus Touch
When using `laser-controls` with Oculus Touch controllers the following effects are present:

- Only the left controller is ever tracked (sometimes cases where it isn't tracked at all).
- When both controllers are added, the right controller is attached to the left controller.
- Supplying the controller with any custom `raycaster` properties stops the controller from being tracked, it just sits in its default position in the scene.
- Occasionally the GearVR controller will be loaded in instead.

Here's a demo: https://codepen.io/PButcher/pen/GxoOBQ

As far as I can tell the `oculus-touch-controls` component is working just fine in 0.8.0.

I experienced this earlier when testing for #3445 and also when poking around for solutions to this `super-hands` issue: https://github.com/wmurphyrd/aframe-super-hands-component/issues/128

- A-Frame Version: 0.8.0
- Platform / Device: Win10, Rift, Firefox
- Reproducible Code Snippet or URL: https://codepen.io/PButcher/pen/GxoOBQ

### PR DESCRIPTION
**Pull request by machenmusik**
Per discussion on #3429, this is a simpler fix avoiding RegExp usage.

### CODE REVIEW

File: src/utils/tracked-controls.js [hunk 1]
```diff
@@ -90,19 +101,24 @@ function findMatchingController (controllers, filterIdExact, filterIdPrefix, fil
...
   for (i = 0; i < controllers.length; i++) {
     controller = controllers[i];
     // Determine if the controller ID matches our criteria
     if (filterIdPrefixes) {
       var matches = false;
-      for (var prefix in filterIdPrefixes) {
-        if (prefix && controller.id.indexOf(prefix) === -1) { matches = true; }
+      for (var j = 0; j < filterIdPrefixes.length; j++) {
+        var prefix = filterIdPrefixes[j];
+        console.log(prefix, ' ?= ', controller.id);
```
Comment (dmarcos) [inline src/utils/tracked-controls.js]: don't need log

File: src/utils/tracked-controls.js [hunk 2]
```diff
@@ -2,6 +2,17 @@ var DEFAULT_HANDEDNESS = require('../constants').DEFAULT_HANDEDNESS;
 var AXIS_LABELS = ['x', 'y', 'z', 'w'];
 var NUM_HANDS = 2; // Number of hands in a pair. Should always be 2.
 
+var splitOnPipeMap = {};
+
+function splitOnPipeOnce (stringToSplit) {
+  var rtn = splitOnPipeMap[stringToSplit];
+  if (!rtn) {
```
Comment (dmarcos) [inline src/utils/tracked-controls.js]: Early return `if (rtn) { return; }`

Comment (machenmusik) [reply src/utils/tracked-controls.js]: (I'm not sure it actually looks better now, but I understand your stylistic preference.)

**Comment by machenmusik** [comment]
The prefix also needs to be passed into tracked-controls, not sure that will survive as array...?

**Comment by machenmusik** [comment]
If we don't mind doing the split each time, can remove the split once map stuff and it will look much more like what is in there now, just not broken.  Is that preferable?

**Comment by machenmusik** [comment]
Have "put the candle back" to provide a minimal fix to what is already in master.
Hopefully we can agree to merge the simple fix, and subsequently discuss optimizations.

**Comment by machenmusik** [comment]
Travis CI failure, but seems entitely unrelated
