### PR TITLE
Clone the properties that are object type into oldData so the update …

### LINKED ISSUE #3403: Line not being updated correctly
**Description:**

On the following example: https://glitch.com/edit/#!/inconclusive-thrill I'm updating the line between to spheres:
```
line.setAttribute('line', {start: posL, end: posR});
``` 
It doesn't work as expected, but If I add `debug: true` to the scene, it works.

I guess it's something related to the latest changes to optimize the set/getAttribute?

### PR DESCRIPTION
**Pull request by dmarcos**
…method is called when they change. We were holding a reference and the deepEqual test was passing and the update method was never called (fix #3403)

-

### CODE REVIEW

**Comment by dmarcos** [comment]
This fixes the problem but introduces extra object copies when instantiating `oldData`. I'm open to alternative solutions.

**Comment by ngokevin** [comment]
Yeah, need to think of another way. The perf hit isn't worth it (also using a Object.keys/forEach/fn creates an array and function over for...in).

I'd say create a method of the line component to accept updates. Assumingly this would be for `tick`ed changes, we wouldn't want to go thru `.setAttribute` in that case.

**Comment by dmarcos** [comment]
Bare in mind we are already instantiating and copying properties to oldData. Strings, numbers, etc. It is allocated memory that is also eventually garbage collected. This patch makes also copies of plain object attributes. In practice the performance won’t change much.

**Comment by dmarcos** [comment]
The problem is not exclusive to line either but to all the component that have vector properties so a specific method to line will not fix the bug.

File: src/core/component.js [hunk 1]
```diff
@@ -522,7 +522,12 @@ function cloneData (data) {
 */
 function extendProperties (dest, source, isSinglePropSchema) {
   if (isSinglePropSchema && (source === null || typeof source !== 'object')) { return source; }
-  return utils.extend(dest, source);
+  var copy = utils.extend(dest, source);
+  Object.keys(copy).forEach(function copyObject (key) {
```
Comment (ngokevin) [inline src/core/component.js]: Use for loop

File: src/core/component.js [hunk 2]
```diff
@@ -522,7 +522,12 @@ function cloneData (data) {
...
+    if (!copy[key] || copy[key].constructor !== Object) { return; }
+    copy[key] = utils.extend({}, copy[key]);
```
Comment (ngokevin) [inline src/core/component.js]: utils.clone

**Comment by fernandojsg** [comment]
I'm afraid that with all the latest optimizations to improve performance we could end up losing consistency if things don't work as expected depending on the type of component (eg: As for pos/rot/sca https://github.com/aframevr/aframe-inspector/issues/534).
I honestly would prefer consistency over performance, as you will always have the option to go deep and use the object3D anyway.
Not sure if it could be even needed something similar to `debug=true` to ensure that the `setAttribute/getAttribute` works as you could expect even if you will lose some performance.

**Comment by ngokevin** [comment]
The getAttribute flow often doesn't matter because for most entities, we never need to retrieve the data, only set. For example, it would be rare to want to retrieve the opacity of an animating button. If we set start/end points of a line and want to keep track, then can store those a in vector in component controlling the line.

The pos/rot/sca was a good perf improvement, with a minor fix on Inspector needed because Inspector was depending on componentchanged event, which also isn't a necessary API. I just simply told Inspector to update the panel when the handles are used. Performance is #1 priority IMO, because sites are unusable otherwise.

this commit should be fine, but worth nothing setAttribute has some overhead that should be avoided on frequent operations.

**Comment by dmarcos** [comment]
@fernandojsg If this PR lands, what other inconsistencies are you worried about? If you modify obj/rot/scale via `setAttribute` componentchanged should fire normally as before. It is when you modify the object3D directly, which is an advanced feature is when the event is not fired because you bypass the `setAttribute` code path.

**Comment by dmarcos** [comment]
This should be ready to go.

**Comment by fernandojsg** [comment]
@dmarcos @ngokevin I believe with this change everything should be fine now. Although I'm not sure about how the getAttribute works, I would expect that If I'm modifying the value accessing directly to the `object3D` that won't get me the expected value, but if I'm setting attributes using `setAttribute` it will always return the same value when I'll call `getAttribute` is that correct?
I totally understand that performance is a top priority here but I was afraid to have edge cases because of the performance optimizations that didn't work as you could expect or as they used to work before these optimizations. I believe we must ensure that the whole api regarding `set/get Attributes` is consistent but expose optimizations to the user knowing that they could lead to inconsistent results if you don't know what you're doing.

**Comment by dmarcos** [comment]
@fernandojsg There are no inconsistencies that I'm aware of. If you modify the object3D directly, `getAttribute` / `setAttribute` will work exactly as before. See example below on: https://rawgit.com/aframevr/aframe/master/examples/showcase/anime-UI/
getset
