### PR TITLE
fix component double-parsing (fixes #912)

### LINKED ISSUE #912: component properties sometimes getting parsed twice
We call `Component.parse` (which calls `schema.parsePropert(y/ies)`) before passing into `buildData` (which also calls `schema.parsePropert(y/ies)`). For property types that don't provide the same result when calling the parser two times in a row, this would break.

### PR DESCRIPTION
**Pull request by ngokevin**
This is blocking adding a property type for assets and the model work:

- Need to change Component to not call `parse` before doing `buildData` since that already does schema parsing. We used to call it because we needed the `style-attr`-parsing. Since we only need that, I changed `buildData` to do `style-attr` parsing for multi-prop schemas.
- Simplified Component.parse/Component.stringify to use the schema functions since it was doing the same thing the schema already handles.
- Bind property parse/stringify to component prop definition to give vec3 parser access to default value

### CODE REVIEW

File: src/core/component.js [hunk 1]
```diff
@@ -111,63 +112,27 @@ Component.prototype = {
...
-
-    Object.keys(processedData).forEach(stringifyProperty);
-
-    return objectStringify(processedData);
-
-    function stringifyProperty (key) {
-      if (!schema[key]) { return; }
-      processedData[key] = schema[key].stringify(processedData[key]);
-    }
+    if (isSingleProp(schema)) { return stringifyProperty(data, schema); }
```
Comment (dmarcos) [inline src/core/component.js]: There was an error returned here if the type was not a vaid one. If I do a type on a type name does it now fail silently?

Comment (dmarcos) [inline src/core/component.js]: I think if a schema specifies a ```type``` and the type is not a valid one we should return a loud error somewhere. I see people declaring a type as ```v3``` or ```vector3``` and not knowing how it's not working.

Comment (ngokevin) [inline src/core/component.js]: the schema module does property type lookup and warnings during the processing stage.

Comment (ngokevin) [inline src/core/component.js]: that already happens at https://github.com/aframevr/aframe/blob/dev/src/core/schema.js#L63

File: src/core/schema.js [hunk 2]
```diff
@@ -59,43 +60,59 @@ function processPropertyDefinition (propDefinition) {
   }
 
   propType = propertyTypes[typeName];
-
   if (!propType) {
     warn('Unknown property type: ' + typeName);
```
Comment (dmarcos) [inline src/core/schema.js]: This should be an error instead of a warning.

File: src/core/schema.js [hunk 3]
```diff
@@ -59,43 +60,59 @@ function processPropertyDefinition (propDefinition) {
   }
 
   propType = propertyTypes[typeName];
-
   if (!propType) {
-    warn('Unknown property type: ' + typeName);
+    error('Unknown property type: ' + typeName);
     return propDefinition;
```
Comment (dmarcos) [inline src/core/schema.js]: Do we still need the return if we trigger an error?

Comment (ngokevin) [inline src/core/schema.js]: ok changed to throw rather than log

**Comment by dmarcos** [comment]
travis is complaining

**Comment by dmarcos** [comment]
This one is ready to go if we just fix the tests

**Comment by ngokevin** [comment]
yeah trying to figure out a failure

**Comment by ngokevin** [comment]
Okay, updated. The component attribute animation was running into `undefined` for the component property value. Also removed a test involving `removeAttribute(component, propName, propValue)` since that doesn't seem necessary.
