### PR TITLE
fix registerPrimitive property merging (fixes #1324)

### LINKED ISSUE #1324: Setting fog: false to a-sky is ignored
**Description:**

`<a-scene fog="color: #fff"><a-sky material="fog: false" rotation='0 -45 0' src='https://www.scenevr.com/prerelease/images/sky.png'></a-sky></a-scene>`

The sky isn't rendered, you just see the fog color instead.

- A-Frame Version: 2.0.0
- Platform/Device: Chrome

### PR DESCRIPTION
**Pull request by ngokevin**
**Description:** Mapped attributes were overwriting defined components.

**Changes proposed:**
- Don't keep track of internal component data. Just do non-destructive updates when possible with `setAttribute(component, propName, propValue)` syntax.
- Move default component initialization to separate method.
- Support merging data with default components + defined components.

### CODE REVIEW

File: src/extras/primitives/registerPrimitive.js [hunk 1]
```diff
@@ -75,6 +69,33 @@ module.exports = function registerPrimitive (name, definition) {
...
+            // Set component properties individually to not overwrite user-defined components.
+            if (componentData instanceof Object && Object.keys(componentData).length) {
+              Object.keys(componentData).forEach(function setProperty (propName) {
+                // Check if component property already defined.
+                var definedData = self.getAttribute(componentName);
+                if (definedData && definedData[propName] !== undefined) { return; }
+
+                self.setAttribute(componentName, propName, componentData[propName]);
+              });
+              return;
```
Comment (cvan) [inline src/extras/primitives/registerPrimitive.js]: perhaps we should `return` only if `self.setAttribute(…)` actually got called?

File: src/extras/primitives/registerPrimitive.js [hunk 2]
```diff
@@ -75,6 +69,33 @@ module.exports = function registerPrimitive (name, definition) {
         }
       },
 
+      applyDefaultComponents: {
+        value: function () {
+          var self = this;
+          var defaultData = cloneObject(this.defaultAttributes);
```
Comment (cvan) [inline src/extras/primitives/registerPrimitive.js]: I wasn't clear from the `cloneObject` docstring - why don't we just use `utils.extend` (which is `Object.assign` under the hood - and polyfilled if not natively available)? `Object.assign` does shallow object cloning, one level only, which seems to be what you want. I'm probably missing something though.

File: src/extras/primitives/registerPrimitive.js [hunk 3]
```diff
@@ -75,6 +69,33 @@ module.exports = function registerPrimitive (name, definition) {
...
+          // Apply default components.
+          Object.keys(defaultData).forEach(function applyDefault (componentName) {
+            var componentData = defaultData[componentName];
+
+            // Set component properties individually to not overwrite user-defined components.
+            if (componentData instanceof Object && Object.keys(componentData).length) {
+              Object.keys(componentData).forEach(function setProperty (propName) {
+                // Check if component property already defined.
+                var definedData = self.getAttribute(componentName);
+                if (definedData && definedData[propName] !== undefined) { return; }
```
Comment (cvan) [inline src/extras/primitives/registerPrimitive.js]: or do we want to just check `propName in definedData`?

File: src/extras/primitives/registerPrimitive.js [hunk 4]
```diff
@@ -75,6 +69,33 @@ module.exports = function registerPrimitive (name, definition) {
...
+          var self = this;
+          var defaultData = cloneObject(this.defaultAttributes);
+
+          // Apply default components.
+          Object.keys(defaultData).forEach(function applyDefault (componentName) {
+            var componentData = defaultData[componentName];
+
+            // Set component properties individually to not overwrite user-defined components.
+            if (componentData instanceof Object && Object.keys(componentData).length) {
+              Object.keys(componentData).forEach(function setProperty (propName) {
```
Comment (cvan) [inline src/extras/primitives/registerPrimitive.js]: I like naming the anonymous functions :+1:

File: src/extras/primitives/registerPrimitive.js (hunk 3 above)
Comment (ngokevin) [inline src/extras/primitives/registerPrimitive.js]: `definedData` can be null

File: src/extras/primitives/registerPrimitive.js (hunk 2 above)
Comment (ngokevin) [inline src/extras/primitives/registerPrimitive.js]: I'll try `deepAssign`, maybe it was written before we had that

File: src/extras/primitives/registerPrimitive.js (hunk 4 above)
Comment (ngokevin) [inline src/extras/primitives/registerPrimitive.js]: I would add it to our linter https://github.com/aframevr/aframe/issues/1033

But I don't want that to catch in our test suite.

File: src/extras/primitives/registerPrimitive.js (hunk 3 above)
Comment (cvan) [inline src/extras/primitives/registerPrimitive.js]: but couldn't `null` be a valid value for some component properties? probably not with primitives. you know better than I do.

Comment (ngokevin) [inline src/extras/primitives/registerPrimitive.js]: Yeah, it's valid. But we're checking for `null` on the entire component dataset here, not just one property.

File: src/extras/primitives/registerPrimitive.js (hunk 1 above)
Comment (ngokevin) [inline src/extras/primitives/registerPrimitive.js]: I'm only returning here to mimic an `if/else`. Not a big fan of that style since it's less clear on the intent, but dmarcos likes that.

Comment (cvan) [inline src/extras/primitives/registerPrimitive.js]: okay, I guess I understand

File: src/extras/primitives/registerPrimitive.js [hunk 5]
```diff
@@ -75,6 +69,33 @@ module.exports = function registerPrimitive (name, definition) {
         }
       },
 
+      applyDefaultComponents: {
+        value: function () {
+          var self = this;
+          var defaultData = utils.extendDeep(this.defaultAttributes);
```
Comment (dmarcos) [inline src/extras/primitives/registerPrimitive.js]: Is it really necessary to create a local copy of the object?

Comment (ngokevin) [inline src/extras/primitives/registerPrimitive.js]: yeah. if you modify this object, it will affect all other entities created from this prototype.

Comment (dmarcos) [inline src/extras/primitives/registerPrimitive.js]: I don't see where is the defaultData object modified.

Comment (ngokevin) [inline src/extras/primitives/registerPrimitive.js]: OK, I think since I removed keeping track of component data, this is no longer needed. Good catch.
