### PR TITLE
setTimeout to let conection close (fix #1765)

### LINKED ISSUE #1765: Composite and anime-ui examples broken in Chrome.
**Description:**

ColladaLoader does not work as expected if the model is defined in `a-assets` in Chrome. The logic of all entities to wait for `a-assets` before loading has introduced a side effect for the `colllada-model` component.  

Chrome behaves in a strange way in the case of  a nested `XMLHttpRequest` to the same URL. The inner request never finishes properly (if this is expected behavior or a bug I don't know). The problem is observed when adding a collada model as part of `a-assets` and a `collada-model` component in the scene that refers to the same url. The file is going to be fetched first by the `a-assets` request. The callback of that request invokes the `load` event that can trigger all the scene entities and their components to load. When the `collada-model` component updates is going to also do an `XMLHttpRequest` to load the model that will never return (notice that the ColladaLoader uses raw `XMLHttpRequest` instead of the `THREE.XHRLoader` so it does not benefit from `THREE.Cache` and the redundant `XMLHttpRequest` is sent).

### PR DESCRIPTION
**Pull request by dmarcos**
**Changes proposed:**
Postpones the load method call so the `XMLHttpRequest` closes before any `load` logic executes

### CODE REVIEW

File: src/core/a-assets.js [hunk 1]
```diff
@@ -82,7 +82,11 @@ registerElement('a-asset-item', {
         xhrLoader.load(src, function (textResponse) {
           THREE.Cache.files[src] = textResponse;
           self.data = textResponse;
-          ANode.prototype.load.call(self);
+          // In Chrome if another XHTMLHttpRequest is sent to the same url
+          // before the previous one closes. The second request never finishes.
+          // setTimeout finishes the first request and lets the logic
+          // triggered by load open subsequent requests.
+          setTimeout(function load () { ANode.prototype.load.call(self); }, 0);
```
Comment (ngokevin) [inline src/core/a-assets.js]: Don't need a 0 right?

Comment (ngokevin) [inline src/core/a-assets.js]: I might link to the issue

**Comment by ngokevin** [comment]
r+wc

File: src/core/a-assets.js [hunk 2]
```diff
@@ -82,7 +82,11 @@ registerElement('a-asset-item', {
         xhrLoader.load(src, function (textResponse) {
           THREE.Cache.files[src] = textResponse;
           self.data = textResponse;
-          ANode.prototype.load.call(self);
+          // In Chrome if another XHTMLHttpRequest is sent to the same url
```
Comment (ngokevin) [inline src/core/a-assets.js]: XMLHttpRequest?

**Comment by ngokevin** [comment]
Thanks for investigating!
